- name: mkdir .k8s_installer
  file: path=/root/.k8s-installer state=directory

- name: copy server.config
  template: src=config-server.yaml.j2  dest=/root/.k8s-installer/config-server.yaml
  notify: restart k8s-installer-server

- name: copy server binary file
  copy: src={{server_path}} dest=/usr/bin/ mode=0755

- name: copy  etcd-client-ca.crt
  copy: src={{localhost_tls_dir}}/etcd-client-ca.crt dest={{project_template_path}}/etcd/

- name: copy etcd-client.crt
  copy: src={{localhost_tls_dir}}/etcd-client.crt dest={{project_template_path}}/etcd/

- name: copy etcd-client.key
  copy: src={{localhost_tls_dir}}/etcd-client.key dest={{project_template_path}}/etcd/

- name: copy server.service
  template: src=server.service.j2 dest=/etc/systemd/system/k8s-installer-server.service

- name: systemctl daemon-reload
  shell: systemctl daemon-reload

- name: start server
  service: name=k8s-installer-server state=started enabled=yes

