- name: copy hosts.txt
  copy: src={{hosts_path}} dest=/tmp/hosts.txt

- name: edit /etc/hosts
  shell: while read line;do grep "$line" /etc/hosts &> /dev/null && [ $? -eq 0 ] || echo "$line" >> /etc/hosts;done < /tmp/hosts.txt

- name: stop firewalld
  shell: systemctl stop firewalld.service
  ignore_errors: yes

- name: SELinux disabled
  shell: setenforce 0
  ignore_errors: yes

- name: Create etcd data dir
  file:
    path: "{{ project_template_path }}/etcd/etcd-data"
    state: directory
    mode: 0700

- name: Copy etcd systemd template to target
  template:
    src: "etcd-systemd-template.j2"
    dest: "/etc/systemd/system/etcd.service"

- name: Copy etcd binary to target
  copy:
    src: "{{ etcd_path}}"
    dest: "/usr/bin/etcd"
    mode: 0755

- name: Copy etcdctl binary to target
  copy:
    src: "{{etcdctl_path}}"
    dest: "/usr/bin/etcdctl"
    mode: 0755
- name: Copy ca to target
  copy: src={{localhost_tls_dir}}/ca.pem dest={{project_template_path}}/etcd/etcd-ca.crt

- name: Copy certs to target
  copy: src={{localhost_tls_dir}}/{{ansible_hostname}}.pem dest={{project_template_path}}/etcd/server.crt

- name: Copy key to target
  copy: src={{localhost_tls_dir}}/{{ansible_hostname}}-key.pem dest={{project_template_path}}/etcd/server.key

- name: Systemctl daemonreload
  shell: systemctl daemon-reload

- name: Enable and start etcd service
  service: name=etcd enabled=yes state=started
